### ISSUE TITLE
Buggy live ACF

### ISSUE THREAD

**Issue by RitheshKumar** [RitheshKumar/VoCopter-Project#4]
I suspect that the vectors involved in the ACF calculation are not being handled well.

**Comment by alexanderlerch** [comment]
Try to be more specific with your issues. Provide detailed information:
- what exactly is the problem
- where is the problem
- how can you reproduce the problem

**Comment by RitheshKumar** [comment]
Problem: 
- Too many dynamic vector allocations;
- ACF looking at only the first maxima after the maximum

**Comment by RitheshKumar** [comment]
Fixed it all! However, I am dynamically clearing and resizing the aucorr vector. Can revise.
